version: '3.7'

services:
  api:
    image: 'library-api:latest'
    ports:
      - 80:3000
    environment:
      - DB=db
    networks:
      - apinet
    depends_on:
      - db
  db:
    image: 'mongo:latest'
    networks:
      - apinet

networks:
  apinet:
